using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FaysalFunds.Domain.Entities
{
    [Table("INVESTMENT_FUNDS")]

    public class InvestmentFunds
    {
        public long ID { get; set; }

        public string FUNDNAME { get; set; }

        public string FUNDCATEGORY { get; set; }
        public string RISKPROFILE { get; set; }
        public string GENDER { get; set; }

        public string MONTHLYPROFILT { get; set; } //SHOULD BE Y OR N
        public string FELPERCENTAGE { get; set; }

        public string ISENABLE { get; set; } //SHOULD BO 0 0R 1
        public DateTime CREATEDON { get; set; }
        public DateTime UPDATEDON { get; set; }
    }
}

//CREATE TABLE KUICK_PAY_ACCESS (
//    ID               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
//    FUNDNAME         VARCHAR2(100),
//    FUNDCATEGORY     VARCHAR2(50),
//    RISKPROFILE      VARCHAR2(50),
//    GENDER           VARCHAR2(10),
//    MONTHLYPROFILT   CHAR(1) CHECK (MONTHLYPROFILT IN ('Y', 'N')), -- Only 'Y' or 'N'
//    FELPERCENTAGE    VARCHAR2(10),
//    ISENABLE         CHAR(1) CHECK (ISENABLE IN ('0', '1')),        -- Only '0' or '1'
//    CREATEDON        DATE DEFAULT SYSDATE,
//    UPDATEDON        DATE DEFAULT SYSDATE
//);
